# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pitch & Prototype Weekend
email: kevin.falting@us.af.mil
description: >- # this means to ignore newlines until "baseurl:"
  Pitch & Prototype Weekend will be August 23 - 25, a weekend-long build sprint. Bring your ideas for a new tool, a piece of software, a better process, or show up ready to contribute to a team. Pitch an idea, build a team, and develop a prototype. Sunday is demo day, that afternoon you'll present your prototype for a Q&A with the board and the community.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://pitchandprototype.com' # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: dev-osan
facebook_group_id: 256151891980498

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
