title: Pitch & Prototype Weekend
description: >- # this means to ignore newlines until "baseurl:"
  Pitch & Prototype Weekend will be August 23 - 25, a weekend-long build sprint. Bring your ideas for a new tool, a piece of software, a better process, or show up ready to contribute to a team. Pitch an idea, build a team, and develop a prototype. Sunday is demo day, that afternoon you'll present your prototype for a Q&A with the board and the community.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://pitchandprototype.com' # the base hostname & protocol for your site, e.g. http://example.com
github_username: dev-osan
facebook_group_id: 256151891980498

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed
